### PR TITLE
base-defconfig: add kconfig for TGL platform

### PR DESCRIPTION
**Pull request by plbossart**
Kernel won't boot without IOV, VMD
Atheros WiFi confirmed working
PCIE_DW to be checked
Touchpad still not working.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
@kv2019i without those changes I can't get the SOF topic/sof-dev to boot on the 14' TGL platform we both received.
Touchpad still not working but otherwise all good.

**Comment by kv2019i** [comment]
I can verify this works with SATA operation in the default "RAID" mode in BIOS. Touchscreen also works, but not the touchpad. Will try to see what is missing still...

**Comment by plbossart** [comment]
@kv2019i @bardliao can you give the update a try?

For touchpad support, the finding from @andy-shev is that we have to use 'blacklist i2c-hid' and then the psmouse module will take care of the touchpad. Don't ask me why.

**Comment by bardliao** [comment]
> @kv2019i @bardliao can you give the update a try on TGL+SDCA hardware?
> 
> For touchpad support, the finding from @andy-shev is that we have to use 'blacklist i2c-hid' and then the psmouse module will take care of the touchpad. Don't ask me why.

Yes, it works on my TGL+SDCA device. It is really helpful. Thanks @plbossart @andy-shev

**Comment by andy-shev** [comment]
FWIW, touchpad got its proper fix: https://git.kernel.org/pub/scm/linux/kernel/git/linusw/linux-pinctrl.git/commit/?h=fixes&id=e8873c0afd34beb67ec492cd648dd0095b911f65

**Pull request merged**
