### PR TITLE
sof-defconfig: add missing IMX8M_SUPPORT

### PR DESCRIPTION
**Pull request by plbossart**
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by dbaluta** [comment]
@plbossart on my machine with this addition the code compiles fine. I wonder what are the differences between our setups:

```
  LD [M]  sound/soc/sof/imx/snd-sof-imx8.ko
  LD [M]  sound/soc/sof/imx/snd-sof-imx8m.ko
  LD [M]  sound/soc/sof/snd-sof-of.ko
  LD [M]  sound/soc/sof/snd-sof-pci.ko
  LD [M]  sound/soc/sof/snd-sof.ko
```

My crosscompiler is rather old 

```
daniel@firefly:~$ aarch64-linux-gnu-gcc --version
aarch64-linux-gnu-gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
```

@xiulipan is there a way we could check this kconfig frag on CI machine?

**Comment by plbossart** [comment]
I used the 0day stuff
````
wget https://raw.githubusercontent.com/intel/lkp-tests/master/sbin/make.cross -O ~/bin/make.cross
chmod +x  ~/bin/make.cross
COMPILER_INSTALL_PATH=~/0day make.cross ARCH=arm64
````

**Comment by dbaluta** [comment]
@plbossart thanks. On my machine sof objects are created but I got a link problem;

```
/home/daniel/0day/gcc-8.2.0-nolibc/aarch64-linux/bin/aarch64-linux-ld: arch/arm64/kernel/head.o: relocation R_AARCH64_ABS32 against `_kernel_offset_le_lo32' can not be used when making a shared object
/home/daniel/0day/gcc-8.2.0-nolibc/aarch64-linux/bin/aarch64-linux-ld: arch/arm64/kernel/efi-entry.stub.o: relocation R_AARCH64_ABS32 against `__efistub_stext_offset' can not be used when making a shared object
arch/arm64/kernel/head.o:(.rodata+0x0): dangerous relocation: unsupported relocation
arch/arm64/kernel/head.o: In function `__primary_switch':
/work/repos/sof/linux/arch/arm64/kernel/head.S:985:(.idmap.text+0x378): dangerous relocation: unsupported relocation
/work/repos/sof/linux/arch/arm64/kernel/head.S:985:(.idmap.text+0x380): dangerous relocation: unsupported relocation
```

This seems unrelated to SOF. 

@xiulipan can we merge this PR and see what happens on CI machines?

**Comment by plbossart** [comment]
ok let's go and see what happens, we need this anyways.

**Pull request merged**
