### PR TITLE
[RFC] base-defconfig: add Dell button support

### PR DESCRIPTION
**Pull request by plbossart**
Not sure if this really has an effect

@juimonen @kv2019i @bardliao would you happen to know which options are required?
When I add these options, it seems that I am able to see some icons when I play/record with the sound settings on. There is an LED for the mic mute that doesn't seem to toggle off/on.

Also wondering how to connect the mute button to the RT715 controls?

### CODE REVIEW

**Comment by juimonen** [comment]
@plbossart for mic mute to work you need:
1) topology with dmic switch and led tokens set (currently pipe-eq-capture should have this and is probably included in hda-generic)
2) those kernel configs you mention
3) mute led patches in kernel but if you are using latest it should be there

you should be able to toggle the mute led from user space with something like:
amixer sset 'Dmic0 Capture Switch' on/off

Now this is the acpi led, so I'm not sure how the actual  button is exactly set/configured.

If you want this to work/reflect in gnome UI, you need to patch pulseaudio with hw volume patch:
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/merge_requests/189
otherwise pulseaudio will use sw volume and never send volume commands to alsa.

For me in lenovo X1 this is working with above stuff, but as said it was partly pre-configured, so not sure how the actual button is set up.

**Comment by juimonen** [comment]
@plbossart I have at least these:
CONFIG_THINKPAD_ACPI=m                                                       
CONFIG_THINKPAD_ACPI_ALSA_SUPPORT=y
CONFIG_LEDS_TRIGGERS=y                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
CONFIG_LEDS_TRIGGER_AUDIO=m

**Comment by plbossart** [comment]
> @plbossart for mic mute to work you need:
> 
> 1. topology with dmic switch and led tokens set (currently pipe-eq-capture should have this and is probably included in hda-generic)

The DMICs are handled by the rt715 chip, we don't use the PCH-attached DMIC for this platform.

> 2. those kernel configs you mention
> 3. mute led patches in kernel but if you are using latest it should be there
> 
> you should be able to toggle the mute led from user space with something like:
> amixer sset 'Dmic0 Capture Switch' on/off

well no, we don't have the usual dmics here. We have to use an RT715 control, but I don't know which one.

> Now this is the acpi led, so I'm not sure how the actual button is exactly set/configured.
> 
> If you want this to work/reflect in gnome UI, you need to patch pulseaudio with hw volume patch:
> https://gitlab.freedesktop.org/pulseaudio/pulseaudio/merge_requests/189
> otherwise pulseaudio will use sw volume and never send volume commands to alsa.

Is there a way you could create a debian package for this? It's a pain to recompile and install such tools

> For me in lenovo X1 this is working with above stuff, but as said it was partly pre-configured, so not sure how the actual button is set up.

What do you mean partly configured, you didnt' use our default SOF config?

**Comment by juimonen** [comment]
@plbossart I've been trying to find easy way to build the debian package for pulseaudio/ubuntu with no luck (debian has its own patching and tools for userspace, much messier than kernel compilation).
And this is mainly because I have to patch more than ubuntu does by default, and didn't have now time to start learning it. 

If you are running pulseaudio v11.1 I have a branch with things ready and it should be pretty fast:
https://gitlab.freedesktop.org/juimonen/pulseaudio/tree/lenovo_test
1) git clone above
2) apt-get install build-dep pulseaudio
3) cd pulseaudio
4) make -j8
5) sudo make install
6) vi /etc/pulse/client.conf (comment in autospawn and set it to "no")
7) pulseaudio --kill
8) pulseaudio -vvvvv (if you want start from boot, undo item 6 and reboot)
9) sudo make uninstall, to remove

With partly configured, I meant that the device was already used in testing before me so I'm not sure what has been done to bios, acpi tables etc. to get the buttons/leds work, or do you need to do anything (this is little bit hazy for me). Kernel I've compiled myself.

**Comment by plbossart** [comment]
> @plbossart I've been trying to find easy way to build the debian package for pulseaudio/ubuntu with no luck (debian has its own patching and tools for userspace, much messier than kernel compilation).
> And this is mainly because I have to patch more than ubuntu does by default, and didn't have now time to start learning it.
> 
> If you are running pulseaudio v11.1 I have a branch with things ready and it should be pretty fast:
> https://gitlab.freedesktop.org/juimonen/pulseaudio/tree/lenovo_test
> 
> 1. git clone above
> 2. apt-get install build-dep pulseaudio
> 3. cd pulseaudio
> 4. make -j8
> 5. sudo make install
> 6. vi /etc/pulse/client.conf (comment in autospawn and set it to "no")
> 7. pulseaudio --kill
> 8. pulseaudio -vvvvv (if you want start from boot, undo item 6 and reboot)
> 9. sudo make uninstall, to remove
> 
> With partly configured, I meant that the device was already used in testing before me so I'm not sure what has been done to bios, acpi tables etc. to get the buttons/leds work, or do you need to do anything (this is little bit hazy for me). Kernel I've compiled myself.

I have 4 SoundWire test devices, so it's  problem if I have to repeat all this multiple times. it's also a problem for QA. I realize packages are a pain but it's the only way to have a copy-exact setup.

**Comment by plbossart** [comment]
@juimonen can you try with topic/sof-dev + this kconfig PR to see if at least on Lenovo X1 the buttons are supported? I just added your settings and calling kconfig-sof-default.sh should generate the right configs.

Also would you know who's got an HDaudio+Dmic Dell device, to double check those buttons with the Dell options?

**Comment by juimonen** [comment]
@plbossart I have a dell device like that, but not sure it has the actual leds... (?) Anyway I will try it

**Comment by juimonen** [comment]
@plbossart yes with this PR the leds work in X1.

**Comment by juimonen** [comment]
@plbossart but if I use the same kernel in my dell device (I don't see leds in this device):
dmesg (and I don't think these have anything to do with sof):
[    5.393712] leds platform::micmute: Setting an LED's brightness failed (-19)
[    6.806371] ACPI Error: AE_AML_PACKAGE_LIMIT, Index (0x0000000FF) is beyond end of object (length 0xF) (20181213/exoparg2-396)
[    6.806385] No Local Variables are initialized for Method [GINF]
[    6.806386] Initialized Arguments for Method [GINF]:  (2 arguments defined for method invocation)
[    6.806387]   Arg0:   00000000bee8e20e <Obj>           Integer 00000000000000FF
[    6.806389]   Arg1:   000000008f3364be <Obj>           Integer 0000000000000000
[    6.806392] ACPI Error: Method parse/execution failed \_SB.GINF, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)
[    6.806396] ACPI Error: Method parse/execution failed \_SB.GADR, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)
[    6.806398] ACPI Error: Method parse/execution failed \_SB.SGOV, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)
[    6.806401] ACPI Error: Method parse/execution failed \_SB.CGWR, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)
[    6.806404] ACPI Error: Method parse/execution failed \_SB.TBFP, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)
[    6.806406] ACPI Error: Method parse/execution failed \_SB.WMTF.WMTF, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)

**Comment by plbossart** [comment]
> @plbossart yes with this PR the leds work in X1.

ok, that's already good!

**Comment by plbossart** [comment]
> @plbossart but if I use the same kernel in my dell device (I don't see leds in this device):
> dmesg (and I don't think these have anything to do with sof):
> [ 5.393712] leds platform::micmute: Setting an LED's brightness failed (-19)
> [ 6.806371] ACPI Error: AE_AML_PACKAGE_LIMIT, Index (0x0000000FF) is beyond end of object (length 0xF) (20181213/exoparg2-396)
> [ 6.806385] No Local Variables are initialized for Method [GINF]
> [ 6.806386] Initialized Arguments for Method [GINF]: (2 arguments defined for method invocation)
> [ 6.806387] Arg0: 00000000bee8e20e Integer 00000000000000FF
> [ 6.806389] Arg1: 000000008f3364be Integer 0000000000000000
> [ 6.806392] ACPI Error: Method parse/execution failed _SB.GINF, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)
> [ 6.806396] ACPI Error: Method parse/execution failed _SB.GADR, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)
> [ 6.806398] ACPI Error: Method parse/execution failed _SB.SGOV, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)
> [ 6.806401] ACPI Error: Method parse/execution failed _SB.CGWR, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)
> [ 6.806404] ACPI Error: Method parse/execution failed _SB.TBFP, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)
> [ 6.806406] ACPI Error: Method parse/execution failed _SB.WMTF.WMTF, AE_AML_PACKAGE_LIMIT (20181213/psparse-531)

Do you mind trying with a Ubuntu kernel to see if these LED work? if not, case closed, but if they do work then we still have a config issue.

**Comment by juimonen** [comment]
@plbossart, sorry don't follow... so my dell device doesn't have physical leds (at least I don't see them) and not sure am I missing some acpi configuration from which these errors are coming. You mean just same kernel that comes with this ubuntu release but these configs added? might take some time for me to set it up...

**Comment by juimonen** [comment]
@plbossart so my main concern was if canonical plans to use same kernel in both lenovo and dell does the same config work in both... now I'm not sure why my dell blurbs these errors. Do I have some bad acpi configuration or leds should not just be enabled in a device which doesn't actually have leds? So is it more general kernel config issue?

**Comment by plbossart** [comment]
Sorry if I confused you @juimonen 
I was only asking you to build topic/sof-dev with the latest Ubuntu .config (+all SOF related ones added) and see if you saw any error messages for buttons/ACPI.

**Comment by libinyang** [comment]
@plbossart This PR hasn't been updated for a long time. Dell's config has been changed. Could you please help update based on the latest kernel? And it may be better to put the button config in a separate file, such as xrun-debug-defconfig?

**Comment by plbossart** [comment]
@libinyang I don't want a new file. Can you clarify what new options have changed and re-check if this works for you?

**Comment by libinyang** [comment]
@plbossart You patch works. (We tested your patch, and it doesn't work at the first time. But we test you patch again in a second time, it works. So it should be our test is wrong in the first time)

**Pull request merged**
