### PR TITLE
base-defconfig: add CONFIG_OF support

### PR DESCRIPTION
**Pull request by plbossart**
this is needed if we want to probe drivers using the OF compatible strings.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
@xiulipan @fredoh9 is there a way we can test this config to see if this impacts CI devices?

@dbaluta FYI, this makes Intel support OF :-)

**Comment by xiulipan** [comment]
@plbossart We can do a simple manually test with kernel build with this kconfig. Will send the test result after test.

**Comment by dbaluta** [comment]
@plbossart good to see this.

**Comment by singalsu** [comment]
It would not hurt to say in commit text what the acronym "OF" is for. Is it known by everyone?

**Comment by plbossart** [comment]
> It would not hurt to say in commit text what the acronym "OF" is for. Is it known by everyone?

https://stackoverflow.com/questions/27978709/whats-the-config-of-in-linux/27980344

**Pull request merged**
