### PR TITLE
amd-defconfig: first addition

### PR DESCRIPTION
**Pull request by plbossart**
This is needed to compile https://github.com/thesofproject/linux/pull/3054

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by ajitkupandey** [comment]
config changes looks good but just wondering if SND_SOC_SOF_NOCODEC would be enabled with above script ? as without that build may fail on testing since machine driver is not included in our PR

**Comment by plbossart** [comment]
@ajitkupandey SND_SOC_SOF_NOCODEC is included in the kconfig-sof-nocodec.sh file.
This is different from the regular kconfig-sof-default.sh

GitHub Actions only compiles, there isn't any functional run. Intel CI takes care of actual tests on our devices. Intel will not test AMD platforms, it'd be your responsibility to hook your own CI to GitHub.

**Comment by ajitkupandey** [comment]
Ok , got it .. Also we need to update READme.md for AMD platform? Do we need to to merge this PR or someone else will take care ?

**Comment by plbossart** [comment]
> Ok , got it .. Also we need to update READme.md for AMD platform? Do we need to to merge this PR or someone else will take care ?

I suggest you add a follow-up PR for AMD-specific changes to README.md. I'll go ahead and merge this.

**Pull request merged**
