### PR TITLE
debug-info-defconfig: add debug symbols needed by pahole

### PR DESCRIPTION
**Pull request by plbossart**
With this we can see the structures

````
pahole -C 'snd_sof_dev' sound/soc/sof/snd-sof.o
struct snd_sof_dev {
	struct device *            dev;                  /*     0     8 */
	spinlock_t                 ipc_lock;             /*     8    72 */
	/* --- cacheline 1 boundary (64 bytes) was 16 bytes ago --- */
	spinlock_t                 hw_lock;              /*    80    72 */
	/* --- cacheline 2 boundary (128 bytes) was 24 bytes ago --- */
	bool                       dspless_mode_selected; /*   152     1 */

	/* XXX 7 bytes hole, try to pack */

	struct sof_firmware        basefw;               /*   160    16 */

	/* XXX last struct has 4 bytes of padding */

	struct snd_soc_component_driver plat_drv;        /*   176   384 */
...
````

### CODE REVIEW

**Comment by plbossart** [comment]
Merge delayed until the Jenkins and CI build servers add 'pahole' as a dependency @fredoh9 @ssavati @marc-hb

**Comment by fredoh9** [comment]
kernel builders have pahole package now.
Let me test build once before merging this.

**Review by fredoh9 — APPROVED** [review]
Internal Linux build index 2114 is the one.

Other than checking on output config file, I was able to see pahole ouput.

Without this PR.
```
(build output directory) $ pahole -C 'snd_sof_dev' sound/soc/sof/snd-sof.o
libbpf: failed to find '.BTF' ELF section in sound/soc/sof/snd-sof.o
pahole: sound/soc/sof/snd-sof.o: Invalid argument
```

pahole output is interesting to compare with source structures.

**Comment by fredoh9** [comment]
After merged, I found a interesting change.
There is extra -dbg package is generated. 220MB vs 26MB.
It is not a problem, but I will double check which package will be chosen by the deploy script.

```
linux-image-6.10.0-rc4-g7f5c1e85f4fe-dbg_6.10.0-rc4-default-topic-sof-dev_amd64.deb	2024-06-27 17:36	220M	 
linux-image-6.10.0-rc4-g7f5c1e85f4fe_6.10.0-rc4-default-topic-sof-dev_amd64.deb	2024-06-27 17:29	26M
```

**Comment by fredoh9** [comment]
deploy script chooses -dbg package. It's first hit by name order

**Comment by fredoh9** [comment]
sorry, it is a critical problem. looks '-dbg' package is not kernel package, looks only with debug information.
Non debug package has to be installed to boot.

I need to revert this PR. Sorry about too early merge.

**Pull request merged**
